ollama:
  base_url: "http://localhost:11434"
  default_model: "mistral-nemo:12b-instruct-2407-q4_K_M"
  timeout: 60
  # Model-specific configurations
  model_configs:
    "gemma3:12b-it-qat":
      temperature: 0.6
      timeout: 60
      top_p: 0.95
      top_k: 64
      repeat_penalty: 0.05
    "qwen3:30b-a3b-instruct-2507-q4_K_M":
      temperature: 0.5
      timeout: 60
      top_p: 0.80
      top_k: 20
      repeat_penalty: 0.05
    "qwen3:8b":
      temperature: 0.4
      timeout: 60
      top_p: 0.95
      top_k: 20
      repeat_penalty: 0.05
    "mistral-nemo:12b-instruct-2407-q4_K_M":
      temperature: 0.5
      timeout: 60
      top_p: 0.95
      top_k: 32
      repeat_penalty: 0.05

output:
  default_format: "text"
  streaming: true

diff:
  default_format: "unified"  # or "split"
